name: Preview PR

on:
  workflow_run:
    workflows: ["Build PR"]
    types:
      - completed

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: preview
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_V8_DEV }}"
          projectId: v8-dev
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
